### Request 1
POST https://daraja-simulation.herokuapp.com/results

### Request 2
POST https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
{"Authorization": "Bearer B3PV0xMGlk1y5fQmTEkwGjzDlsH2"}

{
"ShortCode": "600610",
"ResponseType": "Completed",
"ConfirmationURL": "https://daraja-simulation.herokuapp.com/confirmation",
"ValidationURL": "https://daraja-simulation.herokuapp.com/confirmation"
}
